name: Pylint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies with pip
      run: |
        pip install .
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint --fail-under=9 $(find . -name '*.py' | grep -v -E './frontend|./tests') 
