name: Pylint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python -
    - name: Install dependencies with Poetry
      run: |
        poetry install
        poetry add pylint
    - name: Analysing the code with pylint
      run: |
        pip install .
        pylint --fail-under=9 $(find . -name '*.py' | grep -v -E './frontend|./tests') 
      
