name: Run Pytest

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python -
    - name: Install dependencies with Poetry
      run: |
        /root/.local/bin/poetry install
        /root/.local/bin/poetry add pylint
        /root/.local/bin/poetry add pytest-cov
    - name: Run pytest
      run: |
        pip install .
        cd tests/
        pytest .
        pytest --cov=e2evideo  --cov-report=json
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
