name: Run Pytest

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies with Poetry
      run: |
        pip install .
        pip install pytest
        pip install pytest-cov
    - name: Run pytest
      run: |
        cd tests/
        pytest .
        pytest --cov=e2evideo  --cov-report=json
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
